# Generated by Django 3.1.7 on 2021-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentName', models.TextField(db_column='Parent Name')),
                ('parentEmail', models.EmailField(db_column='Email', max_length=50)),
                ('parentLocation', models.TextField(db_column='Location')),
                ('parentContact', models.CharField(db_column='Contact', max_length=11)),
                ('parentPassword', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': "Student's Parent Info",
            },
        ),
        migrations.CreateModel(
            name='TemporarySP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parentName', models.TextField(db_column='Parent Name')),
                ('parentPassword', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': "Student's Parent Temporary Table",
            },
        ),
    ]
