# Generated by Django 3.1.7 on 2021-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEducator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTutorName', models.CharField(max_length=30)),
                ('homeTutorEmail', models.EmailField(max_length=50)),
                ('university', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('homeTutorLocation', models.CharField(max_length=15)),
                ('homeTutorContact', models.CharField(max_length=11)),
                ('homeTutorPassword', models.CharField(max_length=20)),
                ('homeTutorRating', models.FloatField()),
            ],
            options={
                'db_table': 'Home Educator Info',
            },
        ),
        migrations.CreateModel(
            name='HomeEducatorSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstSubject', models.TextField(db_column='1st Subject')),
                ('secondSubject', models.TextField(db_column='2nd Subject')),
                ('thirdSubject', models.TextField(db_column='3rd Subject')),
            ],
            options={
                'db_table': 'Home Educator Subjects',
            },
        ),
        migrations.CreateModel(
            name='OutsideEducator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outsideTutorName', models.CharField(max_length=30)),
                ('outsideTutorEmail', models.EmailField(max_length=50)),
                ('institute', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('outsideTutorLocation', models.CharField(max_length=15)),
                ('outsideTutorContact', models.CharField(max_length=11)),
                ('outsideTutorPassword', models.CharField(max_length=20)),
                ('outsideTutorRating', models.FloatField()),
            ],
            options={
                'db_table': 'Outside Educator Info',
            },
        ),
        migrations.CreateModel(
            name='OutsideEducatorSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstSubject', models.TextField(db_column='1st Subject')),
                ('secondSubject', models.TextField(db_column='2nd Subject')),
                ('thirdSubject', models.TextField(db_column='3rd Subject')),
            ],
            options={
                'db_table': 'Outside Educator Subjects',
            },
        ),
        migrations.CreateModel(
            name='TemporaryE',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tutorName', models.TextField(db_column='Tutor Name')),
                ('tutorPassword', models.CharField(db_column='Password', max_length=20)),
            ],
            options={
                'db_table': 'Educator Temporary Table',
            },
        ),
    ]
