# Generated by Django 3.1.7 on 2021-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarye',
            name='tutorType',
            field=models.CharField(db_column='Type', default='', max_length=20),
        ),
    ]
